name: Cypress Tests
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress.io
        uses: cypress-io/github-action@v6
